site_name: kform
nav:
  - Home: index.md
  - Getting Started: 
    - Choreo:
      - Getting started: 01-getting-started/choreo/01_getting_started.md
      - Prerequisites: 01-getting-started/choreo/02_prereq.md
    - Kform: 
      - Getting started: 01-getting-started/kform/01_getting_started.md
      - Prerequisites: 01-getting-started/kform/02_prereq.md
  - Kform Language:
    - About: 02-language/01_about.md
    - Files & Directories: 02-language/02_files_dirs.md
#    - Syntax: 02-language/03_syntax.md
    - KForm Resources: 
#      - About: 02-language/resources/about.md
      - Input: 02-language/resources/input.md
      - Output: 02-language/resources/output.md
      - Resource: 02-language/resources/resource.md
      - Data source: 02-language/resources/data_source.md
#      - Data sources: 02-language/resources/data_sources.md
#      - Provider: 02-language/resources/provider.md
#      - Module: 02-language/resources/module.md
    - Kform Resource Attributes:
      - Attributes: 02-language/attributes/about.md
      - Description: 02-language/attributes/description.md
#      - Sensitive: 02-language/attributes/sensitive.md
      - Depends_on: 02-language/attributes/depends_on.md
      - Count: 02-language/attributes/count.md
      - For_each: 02-language/attributes/for_each.md
#      - Provider: 02-language/attributes/provider.md
#      - Lifecycle: 02-language/attributes/lifecycle.md
#  - CLI: 
#    - Cli: 03-cli/01_cli.md
#  - Developer Guide:
#    - About: 04-dev/01_about.md
#    - Provider: 04-dev/02_provider.md
#    - Module: 04-dev/03_module.md
#    - Package library: 04-dev/04_package_library.md
#    - Controller library: 04-dev/05_controller_library.md
#  - Examples/Tutorials:
#    - About: 05-examples/01_about.md
  - Release Notes:
     - "Release Notes": 06-rn/rn.md
#    - "0.0.1": 06-rn/0.0.1.md
  - Community: 
    - Community: 07-community/01_about.md

site_author: Wim Henderickx
site_description: >-
  Kform is a framework that brings the power of 'KRM as code or data' to Kubernetes. 
# repository
repo_name: kform-dev/docs
repo_url: https://github.com/kform-dev/docs
site_url: "https://docs.kform.dev"
theme:
  name: material
  custom_dir: docs/overrides

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  language: en
  features:
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.expand
    - navigation.indexes
    - navigation.sections
    - navigation.tabs.sticky
    - search.suggest
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.action.edit
    - content.tooltips
    #- header.autohide
    #- search.highlight
    #- search.share
    #- search.suggest
    #- toc.integrate
    - toc.follow
    
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: cyan
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: cyan
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Manrope
    code: Fira Mono
  icon:
    logo: fontawesome/solid/sitemap
    repo: fontawesome/brands/github
    edit: material/file-edit-outline
  favicon: assets/logos/Kform-logo-square.svg
  logo: assets/logos/Kform-logo-square.svg

# Plugins
plugins:
  - search
  - minify:
      minify_html: true
  
# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/kform-dev
    # - icon: fontawesome/brands/discord
    #   link: https://discord.gg/fHCNahWR2T
    
extra_css:
  - stylesheets/extra.css

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - md_in_html
  - toc:
      permalink: "#"
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      line_spans: __span
      anchor_linenums: true
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: kform
      repo: docs
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.snippets:
      check_paths: true
      #dedent_subsections: true
      base_path:
        - ./
      url_download: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.blocks.tab:
      alternate_style: true
  - pymdownx.blocks.admonition
  - pymdownx.blocks.definition
  - pymdownx.blocks.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde